language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.0
  - ruby-head
  - jruby
  - rbx
  # - rbx-19mode # currently in active development, may or may not work for your project
# uncomment this line if your project needs to run something other than `rake`:
script: ruby test/test_ruby-mp3info.rb
